### ISSUE TITLE
Default --version option is not working for subcommands

### ISSUE THREAD

**Issue by ericsuhong** [spectreconsole/spectre.console#1567]
**Information**
 - OS: Windows
 - Version: 0.47.0
 - Terminal: Windows Terminal

**Describe the bug**
--version option is working for the root command as expected.

However, when I run --version option for any subcommands, it does not print version and --version option is ignored.

````
mycommand --version
1.0.0

mycommand subcommand --version
... runs the subcommand without printing out the version
````

This is **confusing** because --help option displays --version as a **valid** option for all subcommands by default.

````
mycommand subcommand --help

USAGE:
    mycommand subcommand [OPTIONS]

OPTIONS:
                     DEFAULT
    -h, --help                           Prints help information
    -v, --version                        Prints version information
    -o, --output     test                   My custom option
````

**To Reproduce**
Run any spectre subcommands with --version.

**Expected behavior**
--version MUST NOT be displayed by default as part of --help output for subcommands that do not have explicitly defined --version option.

---
Please upvote :+1: this issue if you are interested in it.

**Comment by ericsuhong** [comment]
The issue is fixed when I enable StrictParsing, but I believe this behavior should still be fixed for normal, default case.

**Comment by MangelMaxime** [comment]
I feel like I have a similar issue when using a "default command".

**Main file** 

```fs
module CommitLinter.Main

open Spectre.Console.Cli
open CommitLinter.Commands

[<EntryPoint>]
let main args =

    let app = CommandApp<GenerateCommand>()

    app
        .WithDescription("Generate changelog based on the Git history.")
        .Configure(fun config ->
            config.Settings.ApplicationName <- "changelog-gen" // Find a name
        )

    app.Run(args)
```

**Command file** 

```fs
namespace CommitLinter.Commands

open Spectre.Console
open Spectre.Console.Cli
open System.ComponentModel
open System.IO

type GenerateSettings() =
    inherit CommandSettings()

    [<CommandOption("-c|--config")>]
    [<Description("Path to the configuration file")>]
    member val Config: string option = None with get, set

type GenerateCommand() =
    inherit Command<GenerateSettings>()
    interface ICommandLimiter<GenerateSettings>

    override __.Execute(context, settings) =
        printfn "Generate command"
        0
```

Then if I run `dotnet run --project myProject.fsproj -- --version` it will prints `Generate command` when I expect it to print the version number of the tool.

Use strict parsing doesn't help, it only report an issue because `--version` is unknown probably because it is using the options config from the `Generate` command only ?

**Comment by FrankRay78** [comment]
Hello @MangelMaxime, your issue is #1216, which I have validated as still occurring in 0.49.1

**Comment by FrankRay78** [comment]
Unfortunately it's still broken in 0.49.1 @ericsuhong 

Here is my command and application:

```csharp
using Spectre.Console;
using Spectre.Console.Cli;


public class EmptyCommand : Command<EmptyCommandSettings>
{
    public override int Execute(CommandContext context, EmptyCommandSettings settings)
    {
        AnsiConsole.MarkupLine("Hello world");
        return 0;
    }
}


public static class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandApp();

        app.Configure(config =>
        {
            config.SetApplicationVersion("1.0");

            config.AddCommand<EmptyCommand>("hello");
        });

        return app.Run(args);
    }
}
```

Help for the subcommand shows the version option, but when the version option is specified, the subcommand executes instead:

![image](https://github.com/user-attachments/assets/198ab5a2-fc3d-428b-b111-81b23ef9e087)

**Expected behaviour**
- Subcommand help doesn't show the version option
- Specifying -v/--version for the subcommand adds these to the remaining arguments (relaxed parsing)
- Specifying -v/--version for the subcommand throws an exception (strict parsing)
